services:
  gateway:
    container_name: wallet-auth-gateway
    image: ghcr.io/carlo451/wallet-auth-gateway:latest
    restart: always
    environment:
      ADMIN_USER: user
      ADMIN_PASSWORD: password
      BASE_URL: https://base_url.com
      SERVER_SSL_ENABLED: true
      SERVER_PORT: 8080
      SERVER_FORWARD_HEADERS_STRATEGY: framework
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_URL: url
      WALLET_SIGN_PRIVATE_KEY_PATH: "file:app/certs/private.pem"
    volumes:
      - ./ssl:/app/ssl:ro
      - ./certs:/app/certs:ro
    ports:
      - "8080:8080"
  database:
    container_name: auth-gateway-postgres
    user: "1000:1000"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-gateway
    ports:
      - "5433:5432"
    volumes:
      - ./gateway-data:/var/lib/postgresql/docker