spring:
  application:
    name: wallet-auth-gateway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-gateway
    username: user
    password: password123
  security:
    user:
      name: user
      password: password
      roles: ADMIN

gateway:
  app:
    network:
      baseurl: https://camo-framework.gentoo-fiordland.ts.net:8443
  bridge:
    assertion:
      issuer: https://camo-framework.gentoo-fiordland.ts.net:8443
      registration-assertion-ttl-seconds: 60
      login-assertion-ttl-seconds: 30
    signing:
      key-id: gateway-signing-key-1
      type: JWT

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tailscale