spring.application.name=auth-gateway

###PORT ###
server.port=8081

### JPA AND DATASOURCE  #####
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.url=jdbc:postgresql://localhost:5433/auth-gateway
spring.datasource.username=user
spring.datasource.password=password123

gateway.app.network.baseurl=http://100.80.20.126:8081